// Runtime deployment config. Plain script (not a module) so facilitators can
// swap values per event without touching application code.
window.GOVERNANCE_ROOM_CONFIG = {
  // Where the game fetches room content from (generated by tools/generate-hashes.mjs).
  roomsUrl: 'config/rooms.json',

  // Shared leaderboard backend (Supabase). Leave both empty to run in
  // local-only mode: codes still validate client-side, but the leaderboard and
  // facilitator view only see teams that played in the same browser.
  // The anon key is publishable by design — protect the table with RLS (see README).
  supabaseUrl: '',        // e.g. 'https://abcd1234.supabase.co'
  supabaseAnonKey: '',
  supabaseTable: 'governance_room_teams',

  // Optional gate for admin.html: if set, the page requires ?key=<adminKey>.
  // A deterrent for curious participants, not real security.
  adminKey: ''
};
